name = "RecurrentNetworkModels"
uuid = "60024d2f-e447-450b-ab68-c236a8c9f1ce"
authors = ["Roger Heirkstad <roger.herikstad@gmail.com>"]
version = "0.1.0"

[deps]
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"

[compat]
Lux = "1.12.4"
